# HTTPS no Auth required
kind: Deployment
apiVersion: apps/v1
metadata:
  name: green
  labels:
    app: cats
    type: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
      type: green
  template:
    metadata:
      labels:
        app: cats
        type: green
    spec:
      containers:
        - name: cats
          image: unfor19/docker-cats:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: APP_NAME
              value: green
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: cats
    type: green
---
apiVersion: networking.k8s.io/v1beta1 # NGINX Ingress Controller supports this version
kind: Ingress
metadata:
  name: green
  annotations:
    cert-manager.io/cluster-issuer: tls-ca-issuer # https://cert-manager.io/docs/usage/ingress/
spec:
  tls:
  - hosts:
    - green.kubemaster.me
    secretName: kubemaster-me-app-tls-secret
  ingressClassName: nginx
  rules:
    - host: green.kubemaster.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: green
              servicePort: 80
