# HTTP no Auth required
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dark
  labels:
    app: cats
    type: dark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats
      type: dark
  template:
    metadata:
      labels:
        app: cats
        type: dark
    spec:
      containers:
        - name: cats
          image: unfor19/docker-cats:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
          env:
            - name: APP_NAME
              value: dark
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dark
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: cats
    type: dark
---
apiVersion: networking.k8s.io/v1beta1 # NGINX Ingress Controller supports this version
kind: Ingress
metadata:
  name: dark
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://auth.kubemaster.me/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://auth.kubemaster.me/oauth2/start?rd=https://$host$escaped_request_uri
spec:
  tls:
  - hosts:
    - dark.kubemaster.me
    secretName: kubemaster-me-app-tls-secret
  ingressClassName: nginx
  rules:
    - host: dark.kubemaster.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: dark
              servicePort: 80
